# Database configuration
[database]
host = "localhost"
port = 3306
name = "mindmate_db"
user = "admin"
password = ""

# Authentication settings
[auth]
cookie_key = "your-secret-key-here"
token_expiry = 86400  # 24 hours

# API keys
[api_keys]
openai_key = ""
groq_key = ""

# Email configuration (if needed)
[email]
server = "smtp.example.com"
port = 587
username = ""
password = ""
